[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
differential-equations = "0.1.1"
nalgebra = "0.33.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
